### ISSUE TITLE
Can't seem to get this working. 

### ISSUE THREAD

**Issue by aixsyd** [ChendiWang/ubibot#1]
I've installed via docker-compose, and its all good. I can add the data source inside grafana, but I'm not sure where to go from there.

If I run node app.js, I get the following error:

`(node:2537) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'filter' of undefined
    at writeToDb (/home/pi/ubibot/app.js:81:32)
    at run (/home/pi/ubibot/app.js:63:3)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2537) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2537) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
at process._tickCallback (internal/process/next_tick.js:68:7)
`

**Comment by loganrouleau** [comment]
Thanks for reaching out! I suspect grabbing the data from your ubibot device isn't working. I'd be curious to see the output of this call for you. Mine contains a list of feeds which have the actual readings. You'll have to swap out the channelId for your own (mine is 12859, that's hardcoded into app.js), I think it's in the ubibot platform configuration somewhere. Also, either hardcode your api key into the url or create an app.properties file containing api.read.key=${key}

Also, for my dashboard I decided to get local weather in my city to compare indoor/outdoor temps. You can get yourself an openweathermaps key and change to your city, or comment out the updateWeather() call in app.js.

https://api.ubibot.io/channels/${channel_id}/feeds.json?api_key=${my_key}:
{
  "result": "success",
  "server_time": "2020-07-08T02:30:25Z",
  "is_truncated": false,
  "cali": null,
  "start": "2020-07-06T03:00:04+00:00",
  "end": "2020-07-08T02:30:08+00:00",
  "sum": null,
  "average": null,
  "min": null,
  "max": null,
  "timezone": "America/Vancouver",
  "num_records": 403,
  "results": 8000,
  "fahrenheit": false,
  "channel": {
    "channel_id": "12859",
    "name": "C-12859",
    "field1": "Temperature",
    "field2": "Humidity",
    "field3": "Light",
    "field4": "Voltage",
    "field5": "WIFI RSSI",
    "field6": "Vibration Index",
    "field7": "Knocks",
    "field8": "External Temperature Probe",
    "field9": "",
    "field10": null,
    "device_id": "3174dea07f1d30f358d7244f602f014ae415c100",
    "latitude": "49.25",
    "longitude": "-123.1333",
    "elevation": null,
    "created_at": "2020-03-28T01:43:28Z",
    "public_flag": "false",
    "user_id": "D46E7D67-9907-4373-8412-64C3B8D92A5C",
    "last_entry_date": "2020-07-08T02:30:20Z",
    "last_entry_id": "63060",
    "vconfig": "{\"field1\":{\"h\":\"0\",\"u\":\"1\"},\"field2\":{\"h\":\"0\",\"u\":\"3\"},\"field3\":{\"h\":\"0\",\"u\":\"4\"},\"field4\":{\"h\":\"0\",\"u\":\"5\"},\"field5\":{\"h\":\"0\",\"u\":\"6\"},\"field6\":{\"h\":\"0\",\"u\":\"7\"},\"field7\":{\"h\":\"0\",\"u\":\"8\"},\"field8\":{\"h\":\"0\",\"u\":\"1\"},\"field9\":{\"h\":\"0\",\"u\":\"9\"}}",
    "cali": null,
    "full_dump": "0",
    "plan_code": "ubibot_free",
    "timezone": null,
    "vpref": "{\"fields\":[{\"key\":\"field1\",\"index\":0,\"visible\":true},{\"key\":\"field2\",\"index\":1,\"visible\":true},{\"key\":\"field3\",\"index\":2,\"visible\":true},{\"key\":\"field4\",\"index\":3,\"visible\":true},{\"key\":\"field5\",\"index\":4,\"visible\":true},{\"key\":\"field6\",\"index\":5,\"visible\":true},{\"key\":\"field7\",\"index\":6,\"visible\":true},{\"key\":\"field8\",\"index\":7,\"visible\":true}],\"v\":1}",
    "vpref_from": "owner",
    "username": "lrouleau"
  },
  "virtual_fields": [],
  "feeds": [
    {
      "created_at": "2020-07-07T19:30:08-07:00",
      "field5": -66
    },
    {
      "created_at": "2020-07-07T19:30:05-07:00",
      "field1": 23.672844,
      "field3": 81.839996,
      "field2": 48
    },
    {
      "created_at": "2020-07-07T19:15:08-07:00",
      "field5": -60
    },
    {
      "created_at": "2020-07-07T19:15:05-07:00",
      "field1": 23.630119,
      "field3": 78.839996,
      "field2": 47
    }
  ]
}
